function [] = CreateOutputFolders(OutputDataFolder, GrpNm, Params)
% this function creates the following output folder structure:
%
%   OutputData+Date
%       ExperimentMatFiles
%       1_SpikeDetection
%       2_NeuronalActivity
%       3_EdgeThresholdingCheck
%       4_NetworkActivity
% Parameters
% ----------
% HomeDir : 
% OutputDataFolder : 
% Date : 
% GrpNm : 
% Returns 
% -------
% None

%% Create the output folders

foldersToCreate = {...
    fullfile(OutputDataFolder, Params.outputDataFolderName), ... 
    fullfile(OutputDataFolder, Params.outputDataFolderName, 'ExperimentMatFiles'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '1_SpikeDetection'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '1_SpikeDetection', '1A_SpikeDetectedData'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '1_SpikeDetection', '1B_SpikeDetectionChecks'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2A_IndividualNeuronalAnalysis'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '1_NodeByGroup'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '2_NodeByAge'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '3_RecordingsByGroup'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '3_RecordingsByGroup', 'HalfViolinPlots'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '4_RecordingsByAge'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '2_NeuronalActivity', '2B_GroupComparisons', '4_RecordingsByAge', 'HalfViolinPlots'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '3_EdgeThresholdingCheck'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4A_IndividualNetworkAnalysis'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '1_NodeByGroup'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '2_NodeByAge'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '3_RecordingsByGroup'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '3_RecordingsByGroup', 'HalfViolinPlots'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '4_RecordingsByAge'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '4_RecordingsByAge', 'HalfViolinPlots'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '5_GraphMetricsByLag'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '6_NodeCartographyByLag'), ...
    fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4B_GroupComparisons', '7_DensityLandscape'), ...
    };


for i = 1:length(GrpNm)
    foldersToCreate{end+1} = fullfile(OutputDataFolder, Params.outputDataFolderName, '4_NetworkActivity', '4A_IndividualNetworkAnalysis', char(GrpNm{i}));
end

if Params.includeNotBoxPlots
    foldersToCreate{end+1} = fullfile(OutputDataFolder, Params.outputDataFolderName, '2B_GroupComparisons', '3_RecordingsByGroup', 'NotBoxPlots');
    foldersToCreate{end+1} = fullfile(OutputDataFolder, Params.outputDataFolderName, '2B_GroupComparisons', '4_RecordingsByAge', 'NotBoxPlots');
end 

for folderIdx = 1:length(foldersToCreate)
    if ~isfolder(foldersToCreate{folderIdx})
        mkdir(foldersToCreate{folderIdx});
    end
end 

addpath(genpath(fullfile(OutputDataFolder, Params.outputDataFolderName)))


end