%{
    Copyright (c) 2024 Axion BioSystems, Inc.
    Contact: support@axion-biosystems.com
    All Rights Reserved
%}
classdef DiscontinuousBlockVectorHeaderEntry < CombinedBlockVectorHeaderEntry
    %CONTINUOUSBLOCKVECTORHEADERENTRY Summary of this class goes here
    %   Detailed explanation goes here

    properties(GetAccess = public, SetAccess = private)
        ChannelIDs;
        DataSetName;
    end

    methods
        function this = DiscontinuousBlockVectorHeaderEntry( ...
                aEntryRecord, ...
                aFileID, ...
                aVersionMajor, ...
                aVersionMinor, ...
                aDataType, ...
                aSampleType, ...
                aSamplingFrequency, ...
                aVoltageScale, ...
                aNumChannelsPerBlock, ...
                aNumSamplesPerBlock, ...
                aVectorHeaderSize, ...
                aBlockHeaderSize, ...
                aBlockVectorStartTime, ...
                aExperimentStartTime, ...
                aAddedDate, ...
                aModifiedDate, ...
                aDuration, ...
                aName, ...
                aDescription, ...
                aDataRegionStart, ...
                aDataRegionLength, ...
                aCombinedBlockVectorSize, ...
                aChannelIDs, ...
                aDataSetName, ...
                aSize)

            this@CombinedBlockVectorHeaderEntry( ...
                aEntryRecord, ...
                aFileID, ...
                aVersionMajor, ...
                aVersionMinor, ...
                aDataType, ...
                aSampleType, ...
                aSamplingFrequency, ...
                aVoltageScale, ...
                aNumChannelsPerBlock, ...
                1,...
                aNumSamplesPerBlock, ...
                aVectorHeaderSize, ...
                aBlockHeaderSize, ...
                aBlockVectorStartTime, ...
                aExperimentStartTime, ...
                aAddedDate, ...
                aModifiedDate, ...
                aDuration, ...
                aName, ...
                aDescription, ...
                aDataRegionStart, ...
                aDataRegionLength, ...
                aCombinedBlockVectorSize);

            this.ChannelIDs = aChannelIDs;
            this.DataSetName = aDataSetName;
        end
    end

    methods(Static)
        function obj = DeserializeFromCombinedBlockVectorHeaderEntry(aEntryRecord, aCombinedBlockVector, aFileID)
            % check if aCombinedBlockVector is a
            % CombinedBlockVectorHeaderEntry
            if ~isa(aCombinedBlockVector, 'CombinedBlockVectorHeaderEntry')
                error('aCombinedBlockVector is not CombinedBlockVectorHeaderEntry instance');
            end

            fStartPos = ftell(aFileID);
            fChannelsLength = fread(aFileID, 1, 'uint32=>uint32');
            fChannelIDs = cell(1, fChannelsLength);

            for i = 1:fChannelsLength
                fChannelIDs{i} = ChannelID(fread(aFileID, 1, 'uint16=>uint16'));
            end

            if (aCombinedBlockVector.NumDataSetsPerBlock ~= 1)
                error('Too Many Data Set Names');
            end
            
            fDataSetNameLength = fread(aFileID, 1, 'int=>int');
            fDataSetName = fread(aFileID, fDataSetNameLength, '*char')';
            % calculate and check CRC
            fDataSize = ftell(aFileID) - fStartPos;

            % Calculate and check CRC
            fseek(aFileID, fStartPos, 'bof');
            fCRCBytes = fread(aFileID, fDataSize, 'uint8');
            fCalcCRC = CRC32(AxisFile.CRC_POLYNOMIAL, AxisFile.CRC_SEED).Compute(fCRCBytes);
            fReadCRC = fread(aFileID, 1, 'uint32');

            if(fReadCRC ~= fCalcCRC)
                error('BlockVectorMetaData checksum was incorrect: %s', fFilename);
            end

            fSize = ...
                4                       + ... %ChannelCount
                length(fChannelIDs) * 2 + ... %Channel Array
                4 + fDataSetNameLength  + ... %DaraSetName
                4;                            %Check sum

            % actual read size
            fReadSize = ftell(aFileID) - fStartPos;

            if(fSize ~= fReadSize)
                error('Unexpected BlockVectorMetadata length');
            end

            obj = DiscontinuousBlockVectorHeaderEntry( ...
                aEntryRecord, ...
                aFileID, ...
                aCombinedBlockVector.VersionMajor, ...
                aCombinedBlockVector.VersionMinor, ...
                aCombinedBlockVector.DataType, ...
                aCombinedBlockVector.SampleType, ...
                aCombinedBlockVector.SamplingFrequency, ...
                aCombinedBlockVector.VoltageScale, ...
                aCombinedBlockVector.NumChannelsPerBlock, ...
                aCombinedBlockVector.NumSamplesPerBlock, ...
                aCombinedBlockVector.VectorHeaderSize, ...
                aCombinedBlockVector.BlockHeaderSize, ...
                aCombinedBlockVector.BlockVectorStartTime, ...
                aCombinedBlockVector.ExperimentStartTime, ...
                aCombinedBlockVector.AddedDate, ...
                aCombinedBlockVector.ModifiedDate, ...
                aCombinedBlockVector.Duration, ...
                aCombinedBlockVector.Name, ...
                aCombinedBlockVector.Description, ...
                aCombinedBlockVector.DataRegionStart, ...
                aCombinedBlockVector.DataRegionLength, ...
                aCombinedBlockVector.CombinedBlockVectorHeaderEntrySize, ...
                fChannelIDs, ...
                fDataSetName, ...
                fSize);
        end
    end
end

