"""Test channel-to-coordinate layout parity with MATLAB.

Run from the repo root::

    uv run python python/test_pipeline_channel_layout.py

Diffs ``meanap.pipeline.channel_layout.get_coords_from_layout()`` against
``python/test_fixtures/channel_layout_reference.npz`` (generated by calling
MATLAB's ``getCoordsFromLayout.m`` directly — see
``python/test_fixtures/gen_coords_reference.m``) for all 5 supported
layouts: MCS60old, MCS60, MCS59, Axion64, Axion16.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(REPO_ROOT / "src"))

from meanap.pipeline.channel_layout import get_coords_from_layout

FIXTURE_PATH = REPO_ROOT / "python" / "test_fixtures" / "channel_layout_reference.npz"
LAYOUTS = ["MCS60old", "MCS60", "MCS59", "Axion64", "Axion16"]


def main() -> None:
    print("=" * 70)
    print("MEA-NAP Python  ▸  Channel Layout Coordinate Parity Test")
    print("=" * 70)

    fixture = np.load(FIXTURE_PATH)
    all_ok = True

    for layout in LAYOUTS:
        py_channels, py_coords = get_coords_from_layout(layout)
        ml_channels = fixture[f"{layout}_channels"]
        ml_coords = fixture[f"{layout}_coords"]

        chan_ok = np.array_equal(py_channels, ml_channels)
        coord_ok = np.allclose(py_coords, ml_coords, atol=1e-9) if chan_ok else False
        ok = chan_ok and coord_ok
        all_ok &= ok

        flag = "✓" if ok else "✗"
        print(f"  {flag} {layout:10s} n={len(py_channels):3d}  "
              f"channels_match={chan_ok}  coords_match={coord_ok}")

    print(f"\n{'=' * 70}")
    print("  → All layouts match MATLAB exactly" if all_ok else "  → Some layouts FAILED")
    print(f"{'=' * 70}")


if __name__ == "__main__":
    main()
