"""Parity test: Python stim detection vs MATLAB detectStimTimes/getStimPatterns.

Ground truth is generated by ``python/test_fixtures/gen_stim_detection_reference.m``
(MATLAB called directly on the two testMEAstim raw recordings). Validates that
the Python port reproduces, per channel:
  - the exact stim onset times,
  - the pattern assignment,
  - blankDurMode / artifactDuration.
"""

from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import scipy.io as sio

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from meanap.stim.detection import detect_stim_times, get_stim_patterns  # noqa: E402
from meanap.pipeline.io import load_raw_recording  # noqa: E402

REPO = Path(__file__).resolve().parents[1]
RAW_DIR = REPO / "local" / "testMEAstim"
FIX_DIR = REPO / "python" / "test_fixtures"

RECORDINGS = [
    "OWT220207_1H_DIV57_HUB45_3UA",
    "OWT220207_1H_DIV57_PER72_3UA",
]

PARAMS = {
    "stimDetectionMethod": "longblank",
    "stimDetectionVal": 150,
    "stimRefractoryPeriod": 2.9,
    "stimDuration": 0.00012,
    "fs": 25000,
    "minBlankingDuration": 0.004,
    "stimTimeDiffThreshold": 0.005,
    "postStimWindowDur": 0.5,
}


def _load_fixture(name: str) -> dict:
    m = sio.loadmat(FIX_DIR / f"{name}_stim_detection_reference.mat")
    elec = m["elecStimTimes"].ravel()  # object array of (1,k) arrays
    return {
        "pattern": m["pattern"].ravel().astype(int),
        "num_stim": m["numStimPerChannel"].ravel().astype(int),
        "elec_stim_times": [np.atleast_1d(np.asarray(e, dtype=float).ravel()) for e in elec],
        "blankDurMode": float(m["blankDurMode"].ravel()[0]),
        "artifactDuration": float(m["artifactDuration"].ravel()[0]),
    }


def main() -> int:
    total_checks = 0
    total_fail = 0
    for name in RECORDINGS:
        fix_path = FIX_DIR / f"{name}_stim_detection_reference.mat"
        if not fix_path.exists():
            print(f"SKIP {name}: fixture missing ({fix_path.name})")
            continue

        dat, channels, fs = load_raw_recording(RAW_DIR / f"{name}.mat")
        dat = dat.astype(np.float64)  # MATLAB detection runs in double
        coords = np.zeros((dat.shape[1], 2))
        info = detect_stim_times(dat, {**PARAMS, "fs": fs}, channels, coords)
        info, patterns = get_stim_patterns(info, PARAMS)

        fx = _load_fixture(name)
        n_ch = len(info)

        # per-channel stim times (exact) + pattern id
        times_ok = pat_ok = 0
        max_time_diff = 0.0
        for c in range(n_ch):
            py_t = info[c].elec_stim_times
            ml_t = fx["elec_stim_times"][c]
            if fx["num_stim"][c] == 0:
                ml_t = np.array([])
            if py_t.shape == ml_t.shape and (py_t.size == 0 or np.allclose(py_t, ml_t, atol=1e-9)):
                times_ok += 1
                if py_t.size:
                    max_time_diff = max(max_time_diff, float(np.max(np.abs(py_t - ml_t))))
            else:
                total_fail += 1
                if total_fail <= 8:
                    print(f"  [{name}] ch{c} times mismatch: py n={py_t.size} ml n={ml_t.size}")
            if info[c].pattern == fx["pattern"][c]:
                pat_ok += 1
            else:
                total_fail += 1
                if total_fail <= 8:
                    print(f"  [{name}] ch{c} pattern: py={info[c].pattern} ml={fx['pattern'][c]}")

        total_checks += 2 * n_ch

        # blankDurMode / artifactDuration
        from meanap.stim.detection import _matlab_mode  # noqa
        non_stim_durs = np.concatenate([
            (info[c].non_stim_blank_ends - info[c].non_stim_blank_starts)
            for c in range(n_ch)
            if info[c].non_stim_blank_starts is not None and info[c].non_stim_blank_starts.size
        ]) if any(info[c].non_stim_blank_starts is not None and info[c].non_stim_blank_starts.size for c in range(n_ch)) else np.array([])
        blank_dur_mode = _matlab_mode(non_stim_durs) if non_stim_durs.size else 0.0
        artifact_dur = blank_dur_mode + PARAMS["postStimWindowDur"] / 1000
        bd_ok = np.isclose(blank_dur_mode, fx["blankDurMode"], atol=1e-9)
        ad_ok = np.isclose(artifact_dur, fx["artifactDuration"], atol=1e-9)
        total_checks += 2
        total_fail += (not bd_ok) + (not ad_ok)

        n_pat = len(patterns)
        print(f"[{name}] channels={n_ch}  stim-times OK {times_ok}/{n_ch} "
              f"(max diff {max_time_diff:.2e}s)  pattern OK {pat_ok}/{n_ch}  "
              f"nPatterns={n_pat}  blankDurMode {'OK' if bd_ok else 'FAIL'} "
              f"({blank_dur_mode:.6g} vs {fx['blankDurMode']:.6g})  "
              f"artifactDuration {'OK' if ad_ok else 'FAIL'}")

    print(f"\nTOTAL: {total_checks - total_fail}/{total_checks} checks passed")
    return 1 if total_fail else 0


if __name__ == "__main__":
    raise SystemExit(main())
